// <auto-generated />
using System;
using CorrectionExerciceEF.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorrectionExerciceEF.Domain.Migrations
{
    [DbContext(typeof(CrowdfundingDbContext))]
    [Migration("20250616100357_AddCheck_DefaultAndUniqueContraints")]
    partial class AddCheck_DefaultAndUniqueContraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorrectionExerciceEF.Domain.Entities.Contrepartie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contrepartie", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contrepartie_Montant", "Montant > 0");
                        });
                });

            modelBuilder.Entity("CorrectionExerciceEF.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Donation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Donation_Montant", "Montant > 0");
                        });
                });

            modelBuilder.Entity("CorrectionExerciceEF.Domain.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("Participation", (string)null);
                });

            modelBuilder.Entity("CorrectionExerciceEF.Domain.Entities.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(7)")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DateMiseEnLigne")
                        .HasColumnType("DATE");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)");

                    b.HasKey("Id");

                    b.ToTable("Projet", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projet_DateFin", "DateFin > DateMiseEnLigne");

                            t.HasCheckConstraint("CK_Projet_DateMiseEnLigne", "DateMiseEnLigne > DateCreation");

                            t.HasCheckConstraint("CK_Projet_Montant", "Montant > 1000");
                        });
                });

            modelBuilder.Entity("CorrectionExerciceEF.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(384)");

                    b.Property<byte[]>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("BINARY(64)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
